export enum ExerciseName {
  // Peito
  SUPINO_RETO = 'SUPINO_RETO',
  SUPINO_INCLINADO = 'SUPINO_INCLINADO',
  SUPINO_DECLINADO = 'SUPINO_DECLINADO',
  CRUCIFIXO = 'CRUCIFIXO',
  CROSSOVER = 'CROSSOVER',

  // Costas
  PUXADA_FRENTE = 'PUXADA_FRENTE',
  PUXADA_ABERTA = 'PUXADA_ABERTA',
  REMADA_CURVADA = 'REMADA_CURVADA',
  REMADA_BAIXA = 'REMADA_BAIXA',
  REMADA_UNILATERAL = 'REMADA_UNILATERAL',
  BARRA_FIXA = 'BARRA_FIXA',

  // Ombros
  DESENVOLVIMENTO = 'DESENVOLVIMENTO',
  ELEVACAO_LATERAL = 'ELEVACAO_LATERAL',
  ELEVACAO_FRONTAL = 'ELEVACAO_FRONTAL',
  CRUCIFIXO_INVERSO = 'CRUCIFIXO_INVERSO',
  ENCOLHIMENTO = 'ENCOLHIMENTO',

  // Bíceps
  ROSCA_DIRETA = 'ROSCA_DIRETA',
  ROSCA_ALTERNADA = 'ROSCA_ALTERNADA',
  ROSCA_MARTELO = 'ROSCA_MARTELO',
  ROSCA_SCOTT = 'ROSCA_SCOTT',
  ROSCA_CONCENTRADA = 'ROSCA_CONCENTRADA',

  // Tríceps
  TRICEPS_POLIA = 'TRICEPS_POLIA',
  TRICEPS_TESTA = 'TRICEPS_TESTA',
  TRICEPS_MERGULHO = 'TRICEPS_MERGULHO',
  TRICEPS_COICE = 'TRICEPS_COICE',

  // Pernas
  AGACHAMENTO_LIVRE = 'AGACHAMENTO_LIVRE',
  LEG_PRESS = 'LEG_PRESS',
  CADEIRA_EXTENSORA = 'CADEIRA_EXTENSORA',
  CADEIRA_FLEXORA = 'CADEIRA_FLEXORA',
  MESA_FLEXORA = 'MESA_FLEXORA',
  STIFF = 'STIFF',
  LEVANTAMENTO_TERRA = 'LEVANTAMENTO_TERRA',
  AFUNDO = 'AFUNDO',
  PASSADA = 'PASSADA',
  PANTURRILHA_EM_PE = 'PANTURRILHA_EM_PE',
  PANTURRILHA_SENTADO = 'PANTURRILHA_SENTADO',

  // Abdômen
  ABDOMINAL_TRADICIONAL = 'ABDOMINAL_TRADICIONAL',
  ABDOMINAL_INFRA = 'ABDOMINAL_INFRA',
  ABDOMINAL_OBLIQUO = 'ABDOMINAL_OBLIQUO',
  PRANCHA = 'PRANCHA',
  ELEVACAO_PERNAS = 'ELEVACAO_PERNAS',

  // Cardio
  ESTEIRA = 'ESTEIRA',
  BICICLETA = 'BICICLETA',
  ELIPTICO = 'ELIPTICO',
  ESCADA = 'ESCADA',
  CORDA = 'CORDA'
}
