export const API_URLS = {
  question: '/question',
  trainings: '/trainings',
  workouts: '/workouts',
  workoutById: (id: string) => `/workouts/${id}`,
  workoutDones: '/workout/dones',
  workoutDonesLastWeekCount: '/workout/dones/stats/last-week/count',
  workoutDonesLastWeekCalories: '/workout/dones/stats/last-week/calories',
  workoutDonesLastWeekMaxWeight: '/workout/dones/stats/last-week/max-weight-exercise',
  workoutDonesQuestion: '/workout/dones/question',
  exercises: '/exercises',
  dietLatest: '/diet/latest',
  dietGenerate: '/diet/generate',
  authRegister: '/auth/register',
  authLogin: '/auth/login',
} as const;
